title: 나의 여행 블로그
description: GitHub Pages + Jekyll
url: "https://serah503.github.io"   # 사용자 도메인만!
baseurl: "/travel-blog"             # 저장소 이름 (앞에 / 포함)

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
